/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"myled.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int is_switch_press()
{
	//if( (BV(0) & GPIOA->IDR)  == 1);
	//Check if switch is pressed or not
	return  (BV(0) & GPIOA->IDR)  == 1 ? 1 : 0 ;
}
int main(void)
{
	led_init();

	//switch Initalisation
	//Enable clock for GPIOA
	RCC->AHB1ENR |= BV(0);

	//Set GPIO A0 as input
	GPIOA->MODER &= ~(BV(1) | BV(0));

	//Set GPIO A0 as low speed
	GPIOA->OSPEEDR &= ~(BV(1) | BV(0));

	//Set GPIO A0 as no pull up no pull down
	GPIOA->PUPDR &= ~(BV(1) | BV(0));

	while( 1 )
	{
		//Check if switch is pressed or not
		if(is_switch_press())
		{
			//if switch is pressed then turn on LED D12, D13, D14, D15 using led_on() function
			led_on();
			DelayMs(1000);
			led_off();
			DelayMs(1000);
			//led_toggle();
		}
		if(is_switch_press())
		{
			led_toggle();
		}
	}



}



