/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stm32f4xx.h>



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
   //LED Initialisation
	//Enable clock for GPIOD
	RCC -> AHB1ENR |= BV(3);

	//SET GPIO D12, D1, D14, D15 as OUTPUT
	GPIOD -> MODER |= (BV(24) | BV(26) | BV(28) | BV(30));
	GPIOD -> MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));

	//SET GPIO D12, D13, D14, D15 as push pull
	GPIOD->OTYPER &= ~(  BV(12)|BV(13)| BV(14)|BV(15)  );

	//SET GPIO D12, D13, D14, D15 as low speed
	GPIOD->OSPEEDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) | BV(28) | BV(29) | BV(30) | BV(31));

	//SET GPIO D12, D13, D14, D15 as no pull up no pull down
	GPIOD->PUPDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) | BV(28) | BV(29) | BV(30) | BV(31));

	while(1)
	{
		//Turn on LED D12, D13, D14, D15
		GPIOD -> ODR |= BV(12);
		DelayMs(200);

		GPIOD -> ODR |= BV(13);
		DelayMs(200);

		GPIOD -> ODR |= BV(14);
		DelayMs(200);

		GPIOD -> ODR |= BV(15);
		DelayMs(200);

		GPIOD -> ODR &= ~(BV(15));
		DelayMs(200);

		GPIOD -> ODR &= ~(BV(14));
		DelayMs(200);

		GPIOD -> ODR &= ~(BV(13));
		DelayMs(200);

		GPIOD -> ODR &= ~(BV(12));
		DelayMs(200);
	}
}
